routes:
  - type: rewrite
    source: /producto/:slug
    destination: /producto/:slug/index.html
  - type: rewrite
    source: /
    destination: /index.html
  - type: rewrite
    source: /armazones
    destination: /index.html
  - type: rewrite
    source: /lentes-de-contacto
    destination: /index.html

  - type: rewrite
    source: /catalogo
    destination: /catalogo/index.html

headers:
  - path: /*
    name: X-Frame-Options
    value: DENY
  - path: /*
    name: Strict-Transport-Security
    value: max-age=31536000; includeSubDomains; preload
  - path: /*
    name: X-Content-Type-Options
    value: nosniff
  - path: /*
    name: Referrer-Policy
    value: strict-origin-when-cross-origin
  - path: /*
    name: Content-Security-Policy-Report-Only
    value: "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://connect.facebook.net https://www.googletagmanager.com https://http2.mlstatic.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https:; font-src 'self' data: https://fonts.gstatic.com; connect-src 'self' https://lensique-pos.onrender.com https://www.facebook.com https://www.google-analytics.com https://api.mercadopago.com; frame-src 'self' https://www.facebook.com https://www.mercadopago.com.mx https://www.mercadopago.com;"
