routes:
  - type: rewrite
    source: /producto/:slug
    destination: /producto/:slug/index.html
  - type: rewrite
    source: /
    destination: /index.html
  - type: rewrite
    source: /armazones
    destination: /index.html
  - type: rewrite
    source: /lentes-de-contacto
    destination: /index.html
  - type: rewrite
    source: /pago/exito
    destination: /index.html

